import { Category, EventWithStatus } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Technical & Coding",
    slug: "technical",
    icon: "code-2",
    color: "#6366F1",
    description: "Hackathons, competitive programming, AI/ML, and dev conferences",
    sort_order: 1,
    created_at: new Date().toISOString(),
    event_count: 14,
  },
  {
    id: "cat-2",
    name: "Cultural & Arts",
    slug: "cultural",
    icon: "music",
    color: "#EC4899",
    description: "Music battles, dance fests, drama, and fine arts festivals",
    sort_order: 2,
    created_at: new Date().toISOString(),
    event_count: 9,
  },
  {
    id: "cat-3",
    name: "Management & B-Plan",
    slug: "management",
    icon: "briefcase",
    color: "#F59E0B",
    description: "Case studies, startup pitches, marketing and consulting summits",
    sort_order: 3,
    created_at: new Date().toISOString(),
    event_count: 7,
  },
  {
    id: "cat-4",
    name: "Gaming & Esports",
    slug: "gaming",
    icon: "trophy",
    color: "#8B5CF6",
    description: "LAN tournaments, battle royale leagues, and speedrunning",
    sort_order: 4,
    created_at: new Date().toISOString(),
    event_count: 5,
  },
  {
    id: "cat-5",
    name: "Workshops & Bootcamps",
    slug: "workshops",
    icon: "presentation",
    color: "#10B981",
    description: "Hands-on masterclasses with verified industry certificates",
    sort_order: 5,
    created_at: new Date().toISOString(),
    event_count: 12,
  },
  {
    id: "cat-6",
    name: "Sports & Athletics",
    slug: "sports",
    icon: "award",
    color: "#EF4444",
    description: "Inter-collegiate cricket, football, basketball, and track",
    sort_order: 6,
    created_at: new Date().toISOString(),
    event_count: 6,
  },
  {
    id: "cat-7",
    name: "Design & Media",
    slug: "design",
    icon: "cpu",
    color: "#06B6D4",
    description: "UI/UX sprints, filmmaking, photography, and graphic battles",
    sort_order: 7,
    created_at: new Date().toISOString(),
    event_count: 8,
  },
  {
    id: "cat-8",
    name: "Entrepreneurship",
    slug: "entrepreneurship",
    icon: "star",
    color: "#F97316",
    description: "E-Cell summits, investor meetups, and incubator demo days",
    sort_order: 8,
    created_at: new Date().toISOString(),
    event_count: 10,
  },
];

const now = new Date();
const liveStart = new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString();
const liveEnd = new Date(now.getTime() + 6 * 60 * 60 * 1000).toISOString();

const upcomingStart1 = new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString();
const upcomingEnd1 = new Date(now.getTime() + 48 * 60 * 60 * 1000).toISOString();

const upcomingStart2 = new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString();
const upcomingEnd2 = new Date(now.getTime() + 6 * 24 * 60 * 60 * 1000).toISOString();

const upcomingStart3 = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString();
const upcomingEnd3 = new Date(now.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString();

const upcomingStart4 = new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString();
const upcomingEnd4 = new Date(now.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString();

const completedStart = new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString();
const completedEnd = new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_EVENTS: EventWithStatus[] = [
  {
    id: "evt-hackindia-2026",
    slug: "hackindia-national-hackathon-2026",
    title: "HackIndia 2026: The National AI & Web3 Hackathon",
    short_description: "36 hours of non-stop innovation, cutting-edge AI architectures, and decentralized apps with mentors from top tech giants.",
    description: `HackIndia 2026 brings together over 1,500 elite collegiate developers, designers, and innovators across India for an intense 36-hour sprint.\n\nTracks include Generative AI Agents, Zero-Knowledge Cryptography, Autonomous Robotics, and Sustainable Climate Tech. Mentorship from senior engineering leads at Google, Microsoft, and leading Web3 foundations.\n\nTop teams will pitch on the grand stage before venture capital partners and win from a ₹5,00,000 cash prize pool!`,
    category_id: "cat-1",
    college_id: "col-iitd",
    organizer_id: "org-cs-club",
    banner_url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80",
    venue: "Main Auditorium & Computing Complex",
    address: "Hauz Khas, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    mode: "hybrid",
    meeting_url: "https://meet.google.com/live-hackindia",
    start_at: liveStart,
    end_at: liveEnd,
    registration_deadline: liveStart,
    max_participants: 500,
    eligibility: "Open to all enrolled undergraduate and graduate students with a valid college ID.",
    rules: "Teams of 2 to 4 members. Pre-written code is strictly prohibited. All projects must be committed to public GitHub repositories created at kickoff.",
    prize_info: "₹2,50,000 First Place · ₹1,50,000 Second Place · ₹1,00,000 Track Winners + Direct Interview Waivers",
    has_certificate: true,
    status: "published",
    approved: true,
    approved_by: "admin",
    published_at: new Date().toISOString(),
    featured: true,
    tags: ["Hackathon", "AI/ML", "Web3", "Cash Prize", "Certificate"],
    meta_title: "HackIndia 2026 — National AI Hackathon",
    meta_description: "Participate in India's biggest collegiate AI & Web3 hackathon with ₹5 Lakhs in prizes.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category_name: "Technical & Coding",
    category_slug: "technical",
    category_icon: "code-2",
    category_color: "#6366F1",
    college_name: "Indian Institute of Technology Delhi",
    college_slug: "iit-delhi",
    college_logo_url: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=120&h=120&q=80",
    organizer_name: "IITD Computer Science Society",
    organizer_avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&h=120&q=80",
    computed_status: "LIVE",
    registration_count: 486,
    interest_count: 820,
    attendance_count: 420,
  },
  {
    id: "evt-technosphere-2026",
    slug: "technosphere-annual-tech-symposium-2026",
    title: "Technosphere 2026: Annual Tech Symposium",
    short_description: "Three action-packed days of competitive robotics, quantum computing keynotes, and drone racing leagues.",
    description: `Technosphere is Central India's premier annual technical festival. Featuring 25+ flagship events spanning robotics combat, autonomous drone challenges, algorithm design championships, and keynote talks by pioneering scientists.`,
    category_id: "cat-1",
    college_id: "col-bits",
    organizer_id: "org-robotics",
    banner_url: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
    venue: "BITS Pilani Campus Ground",
    address: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    mode: "offline",
    meeting_url: null,
    start_at: upcomingStart1,
    end_at: upcomingEnd1,
    registration_deadline: upcomingStart1,
    max_participants: 1200,
    eligibility: "Engineering and technology students from recognized institutions.",
    rules: "Participants must carry safety gear for robotics arenas. Decisions of the technical committee are final.",
    prize_info: "₹3,00,000 Grand Prize Pool across 12 competitive tracks.",
    has_certificate: true,
    status: "published",
    approved: true,
    approved_by: "admin",
    published_at: new Date().toISOString(),
    featured: true,
    tags: ["Robotics", "Drones", "Competitive", "Symposium"],
    meta_title: "Technosphere 2026 — BITS Pilani",
    meta_description: "Annual tech symposium featuring robotics combat and drone racing.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category_name: "Technical & Coding",
    category_slug: "technical",
    category_icon: "code-2",
    category_color: "#6366F1",
    college_name: "BITS Pilani",
    college_slug: "bits-pilani",
    college_logo_url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=120&h=120&q=80",
    organizer_name: "Robotics & Innovation Club",
    organizer_avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80",
    computed_status: "UPCOMING",
    registration_count: 654,
    interest_count: 1120,
    attendance_count: 0,
  },
  {
    id: "evt-rhythm-beats-2026",
    slug: "rhythm-and-beats-battle-of-bands-2026",
    title: "Rhythm & Beats: National Inter-College Battle of Bands",
    short_description: "Electrifying live performances, rock fusion faceoffs, and acoustic showdowns judged by celebrity musicians.",
    description: `Get ready for high-octane rock, jazz, classical fusion, and indie anthems! 16 finalist bands battle on the illuminated open-air amphitheater with professional lighting and sound rigs.`,
    category_id: "cat-2",
    college_id: "col-xaviers",
    organizer_id: "org-music-society",
    banner_url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80",
    venue: "St. Xavier's Amphitheatre",
    address: "5 Mahapalika Marg, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    mode: "offline",
    meeting_url: null,
    start_at: upcomingStart2,
    end_at: upcomingEnd2,
    registration_deadline: upcomingStart2,
    max_participants: 800,
    eligibility: "College bands with minimum 3 and maximum 8 members.",
    rules: "Original compositions receive bonus points. Performance time limit is 20 minutes including sound check.",
    prize_info: "₹1,50,000 + Studio Recording Contract with SoundScape Records.",
    has_certificate: true,
    status: "published",
    approved: true,
    approved_by: "admin",
    published_at: new Date().toISOString(),
    featured: true,
    tags: ["Music", "Live Band", "Battle of the Bands", "Rock"],
    meta_title: "Rhythm & Beats 2026 — Battle of Bands",
    meta_description: "National collegiate battle of bands at St. Xavier's Mumbai.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category_name: "Cultural & Arts",
    category_slug: "cultural",
    category_icon: "music",
    category_color: "#EC4899",
    college_name: "St. Xavier's College, Mumbai",
    college_slug: "st-xaviers-mumbai",
    college_logo_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=120&h=120&q=80",
    organizer_name: "Xavier's Music Circle",
    organizer_avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80",
    computed_status: "UPCOMING",
    registration_count: 512,
    interest_count: 980,
    attendance_count: 0,
  },
  {
    id: "evt-venture-forge-2026",
    slug: "venture-forge-national-bplan-challenge",
    title: "VentureForge: National Startup B-Plan Summit",
    short_description: "Pitch your venture to top angel syndicates, receive term sheet evaluations, and unlock seed grants.",
    description: `VentureForge is India's most prestigious collegiate entrepreneurship summit. More than 40 leading angel investors and venture capitalists assemble to hear high-growth pitches in fintech, healthtech, climatetech, and SaaS.`,
    category_id: "cat-3",
    college_id: "col-iimb",
    organizer_id: "org-ecell",
    banner_url: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1200&q=80",
    venue: "IIM Bangalore Executive Conference Hall",
    address: "Bannerghatta Main Rd, Bengaluru",
    city: "Bengaluru",
    state: "Karnataka",
    mode: "hybrid",
    meeting_url: "https://zoom.us/j/ventureforge-summit",
    start_at: upcomingStart3,
    end_at: upcomingEnd3,
    registration_deadline: upcomingStart3,
    max_participants: 300,
    eligibility: "Student-founded startups with minimum viable prototype or pilot data.",
    rules: "5-minute pitch followed by 5 minutes of Q&A with the jury panel.",
    prize_info: "₹10,00,000 Seed Grant Pool + Incubation at NSRCEL",
    has_certificate: true,
    status: "published",
    approved: true,
    approved_by: "admin",
    published_at: new Date().toISOString(),
    featured: true,
    tags: ["Startup", "Pitch", "Funding", "Entrepreneurship"],
    meta_title: "VentureForge B-Plan Challenge — IIM Bangalore",
    meta_description: "Pitch to leading angels and win seed funding at IIMB.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category_name: "Management & B-Plan",
    category_slug: "management",
    category_icon: "briefcase",
    category_color: "#F59E0B",
    college_name: "IIM Bangalore",
    college_slug: "iim-bangalore",
    college_logo_url: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=120&h=120&q=80",
    organizer_name: "E-Cell IIMB",
    organizer_avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&h=120&q=80",
    computed_status: "UPCOMING",
    registration_count: 240,
    interest_count: 730,
    attendance_count: 0,
  },
  {
    id: "evt-fullstack-ai-bootcamp",
    slug: "fullstack-ai-agents-hands-on-masterclass",
    title: "Building Autonomous AI Agents with LangChain & Next.js",
    short_description: "Interactive full-day masterclass covering multi-agent orchestration, RAG vector pipelines, and production deployments.",
    description: `Step-by-step masterclass with hands-on labs. Build and deploy production-ready AI agents capable of reasoning, utilizing external tools, and executing complex workflows. All attendees receive verified credentials.`,
    category_id: "cat-5",
    college_id: "col-iitd",
    organizer_id: "org-cs-club",
    banner_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    venue: "Online Webinar + Discord Lab Room",
    address: null,
    city: null,
    state: null,
    mode: "online",
    meeting_url: "https://meet.google.com/ai-agents-workshop",
    start_at: upcomingStart4,
    end_at: upcomingEnd4,
    registration_deadline: upcomingStart4,
    max_participants: 1000,
    eligibility: "Familiarity with JavaScript/TypeScript or Python recommended.",
    rules: "Lab exercises must be submitted before deadline to qualify for certificate.",
    prize_info: "Exclusive API credits from cloud sponsors + Certificate of Completion.",
    has_certificate: true,
    status: "published",
    approved: true,
    approved_by: "admin",
    published_at: new Date().toISOString(),
    featured: false,
    tags: ["AI Agents", "Workshop", "LangChain", "Certificate", "Online"],
    meta_title: "AI Agents Masterclass — IIT Delhi",
    meta_description: "Build autonomous multi-agent systems with industry practitioners.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category_name: "Workshops & Bootcamps",
    category_slug: "workshops",
    category_icon: "presentation",
    category_color: "#10B981",
    college_name: "Indian Institute of Technology Delhi",
    college_slug: "iit-delhi",
    college_logo_url: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=120&h=120&q=80",
    organizer_name: "IITD Computer Science Society",
    organizer_avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&h=120&q=80",
    computed_status: "UPCOMING",
    registration_count: 890,
    interest_count: 1450,
    attendance_count: 0,
  },
  {
    id: "evt-esports-championship",
    slug: "colosseum-national-esports-championship-2026",
    title: "Colosseum 2026: National Collegiate Esports League",
    short_description: "Valorant & BGMI tournament with 64 qualifying college rosters streaming live to tens of thousands of viewers.",
    description: `Colosseum is the ultimate collegiate battleground for competitive gamers. 5v5 Tactical Shooter (Valorant) and 4-player Squads (BGMI) compete across group stages, playoffs, and LAN Grand Finals with live casting and caster booths.`,
    category_id: "cat-4",
    college_id: "col-bits",
    organizer_id: "org-robotics",
    banner_url: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    venue: "BITS Pilani Auditorium & LAN Arena",
    address: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    mode: "hybrid",
    meeting_url: "https://twitch.tv/colosseum-esports",
    start_at: completedStart,
    end_at: completedEnd,
    registration_deadline: completedStart,
    max_participants: 256,
    eligibility: "Verified students with eligible game IDs and anti-cheat client enabled.",
    rules: "Tournament follows official VCT and BGMI competitive guidelines.",
    prize_info: "₹2,00,000 Total Prize Pool + Gaming Peripheral Sponsor Kits.",
    has_certificate: true,
    status: "published",
    approved: true,
    approved_by: "admin",
    published_at: new Date().toISOString(),
    featured: false,
    tags: ["Esports", "Valorant", "BGMI", "Gaming"],
    meta_title: "Colosseum 2026 — Collegiate Esports",
    meta_description: "National collegiate Valorant and BGMI championship.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category_name: "Gaming & Esports",
    category_slug: "gaming",
    category_icon: "trophy",
    category_color: "#8B5CF6",
    college_name: "BITS Pilani",
    college_slug: "bits-pilani",
    college_logo_url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=120&h=120&q=80",
    organizer_name: "BITS Gaming Association",
    organizer_avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80",
    computed_status: "COMPLETED",
    registration_count: 256,
    interest_count: 890,
    attendance_count: 240,
  },
];
